[run]
init_cmds = [                      # Commands run in start
  ["go", "install"],
  ["go", "build", "-o", "piclimbing"],
  ["./piclimbing", "-strength-device", "simulator/load_cell.device", "-encoder-device", "/dev/input/event21", "-v", "3", "-strength-gather-time", "20"]
]
cmds = [                           # Commands to run
  ["go", "install"],
  ["go", "build", "-o", "piclimbing"],
  ["./piclimbing", "-strength-device", "simulator/load_cell.device", "-encoder-device", "/dev/input/event21", "-v", "3", "-strength-gather-time", "20"]
]
watch_all = true                   # Watch all sub-directories
watch_dirs = ["graph", "speed", "strength"]                    # Directories to watch
watch_exts = [".go"]               # Extensions to watch
env_files = []                     # Load env vars from files
ignore = [".git", "node_modules"]  # Directories to exclude from watching
ignore_files = []                  # Regexps for ignoring specific notifies
follow_symlinks = false            # Enable/disable following symbolic links of sub directories
build_delay = 120                 # Minimal interval to Trigger build event
interrupt_timout = 15              # Time to wait until force kill
graceful_kill = false              # Wait for exit and before directly kill

[sync]
listen_addr = ":5050"
remote_addr = ":5050"
